name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Diagnose DNS and network
        run: |
          echo "Tailscale status:"
          tailscale status
          echo "Tailscale IPv4:"
          tailscale ip -4
          echo "Trying DNS against your servers:"
          dig gitea.docker-1.gwebs.ca @192.168.10.5 || echo "DNS10.5 FAIL"
          dig gitea.docker-1.gwebs.ca @192.168.15.5 || echo "DNS15.5 FAIL"
          dig gitea.docker-1.gwebs.ca || echo "Default NS FAIL"
          echo "Trying to ping DNS servers:"
          ping -c2 192.168.10.5 || echo "ping to 10.5 failed"
          ping -c2 192.168.15.5 || echo "ping to 15.5 failed"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Make sure we can log in to your local registry via Tailscale. Set secrets in GitHub.
      - name: Log in to local Docker registry
        uses: docker/login-action@v3
        with:
          registry: gitea.docker-1.gwebs.ca
          username: ${{ secrets.GITEA_REGISTRY_USER }}
          password: ${{ secrets.GITEA_REGISTRY_PASS }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            gitea.docker-1.gwebs.ca/gabriel/jokedejean:latest